### ISSUE TITLE
URGENT Backend Removing Opponent Claim or Something

### ISSUE THREAD

**Issue by PhantomLel** [Leek727/ChessSchedule#18]
```
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/socketio/server.py", line 731, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/socketio/server.py", line 756, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/flask_socketio/__init__.py", line 826, in _handle_event
    ret = handler(*args)
  File "/workspace/ChessSchedule/chessschedule/routes/socket_routes.py", line 191, in game_result
    success = room.game_result(data["player_uuid"], data["result"])
  File "/workspace/ChessSchedule/chessschedule/models/room.py", line 165, in game_result
    self.claims.remove(opponent_claim)
ValueError: list.remove(x): x not in list
```
@clayrock78 get in here

**Comment by clayrock78** [comment]
This is not a crazy issue, I'll fix it now

**Comment by PhantomLel** [comment]
Yeah but I figured making an issue was the easiest way for you to see it

**Comment by clayrock78** [comment]
fixed 👍
