### ISSUE TITLE
Testing Notes

### ISSUE THREAD

**Issue by clayrock78** [Leek727/ChessSchedule#22]
## IF YOU HAVE NOTES OR LOGS PUT THEM ON THIS ISSUE
names wrap over really big gap on join screen
update leaderboard and pairings as wins happen
end game - bye player stays on pairing screen
pairings are not showing up - second round of testing
doesn't put player in game ? ? ? ? ? ?
current leaderboard instead of leaderboard
both players clicked the same thing and it it still said "waiting for other player" jace will send the JS console error to abdullah
game start before player information is entered causes a bug where the player goes to leaderboard - disagreement between server leaderboard and client
sitout does not advance from please wait screen
query server to see if room is still open often

Exception in thread Thread-240:
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/threading.py", line 932, in _bootstrap_inner
127.0.0.1 - - [02/Dec/2022 17:23:17] "POST /socket.io/?EIO=4&transport=polling&t=OJJtIji&sid=SGd2WMvI3yjQLIKjAAAI HTTP/1.1" 200 -
    self.run()
  File "/home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/socketio/server.py", line 804, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/socketio/server.py", line 831, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/flask_socketio/__init__.py", line 288, in _handler
    return self._handle_event(handler, message, namespace, sid, *args)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/flask_socketio/__init__.py", line 909, in _handle_event
    ret = handler(*args)
  File "/workspace/ChessSchedule/chessschedule/routes/socket_routes.py", line 106, in get_all_players
    player_list_update(get_room_uuid(data["room_uuid"]))
  File "/workspace/ChessSchedule/chessschedule/routes/socket_routes.py", line 42, in player_list_update
    data = {"players": [vars(player) for player in room.players]}
AttributeError: 'NoneType' object has no attribute 'players'

RESTART SERVER AND CLIENT TRIES TO LOAD LEADERBOARD CAUSING THIS ERROR ^

**Comment by Leek727** [comment]
## Bugs
sitout person does not progress
game does not automatically move on
pairings not showing on admin board
didnt go to pairing page
both waiting
admin next round button doesnt work
both confirmed but not sitting down
end game doesnt work for people - randomly breaks for people
leaderboard is empty
leaderboard not updating

# cosmetic
current leaderboard
